I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/variables.rpy", line 103, in script
    return
Exception: Could not find return label (u'game/day+2.rpy', 1639778583, 39).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/variables.rpy", line 103, in script
    return
  File "renpy/ast.py", line 1562, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/day+2.rpy', 1639778583, 39).

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
Solstice 1.0
Fri Dec 17 17:10:17 2021
